// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fir_filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fir_filter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fir_filter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<14> fir_filter::ap_ST_fsm_state1 = "1";
const sc_lv<14> fir_filter::ap_ST_fsm_state2 = "10";
const sc_lv<14> fir_filter::ap_ST_fsm_state3 = "100";
const sc_lv<14> fir_filter::ap_ST_fsm_state4 = "1000";
const sc_lv<14> fir_filter::ap_ST_fsm_pp0_stage0 = "10000";
const sc_lv<14> fir_filter::ap_ST_fsm_state9 = "100000";
const sc_lv<14> fir_filter::ap_ST_fsm_state10 = "1000000";
const sc_lv<14> fir_filter::ap_ST_fsm_state11 = "10000000";
const sc_lv<14> fir_filter::ap_ST_fsm_state12 = "100000000";
const sc_lv<14> fir_filter::ap_ST_fsm_pp1_stage0 = "1000000000";
const sc_lv<14> fir_filter::ap_ST_fsm_state17 = "10000000000";
const sc_lv<14> fir_filter::ap_ST_fsm_state18 = "100000000000";
const sc_lv<14> fir_filter::ap_ST_fsm_state19 = "1000000000000";
const sc_lv<14> fir_filter::ap_ST_fsm_state20 = "10000000000000";
const bool fir_filter::ap_const_boolean_1 = true;
const sc_lv<32> fir_filter::ap_const_lv32_5 = "101";
const sc_lv<32> fir_filter::ap_const_lv32_A = "1010";
const sc_lv<32> fir_filter::ap_const_lv32_7 = "111";
const sc_lv<32> fir_filter::ap_const_lv32_8 = "1000";
const sc_lv<32> fir_filter::ap_const_lv32_C = "1100";
const sc_lv<32> fir_filter::ap_const_lv32_D = "1101";
const sc_lv<32> fir_filter::ap_const_lv32_1 = "1";
const sc_lv<32> fir_filter::ap_const_lv32_4 = "100";
const bool fir_filter::ap_const_boolean_0 = false;
const sc_lv<1> fir_filter::ap_const_lv1_0 = "0";
const sc_lv<32> fir_filter::ap_const_lv32_9 = "1001";
const sc_lv<32> fir_filter::ap_const_lv32_6 = "110";
const sc_lv<32> fir_filter::ap_const_lv32_2 = "10";
const sc_lv<32> fir_filter::ap_const_lv32_3 = "11";
const sc_lv<32> fir_filter::ap_const_lv32_B = "1011";
const sc_lv<1> fir_filter::ap_const_lv1_1 = "1";
const sc_lv<6> fir_filter::ap_const_lv6_39 = "111001";
const sc_lv<32> fir_filter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<6> fir_filter::ap_const_lv6_0 = "000000";
const sc_lv<42> fir_filter::ap_const_lv42_3FFFFFFFE86 = "111111111111111111111111111111111010000110";
const sc_lv<6> fir_filter::ap_const_lv6_3F = "111111";
const sc_lv<32> fir_filter::ap_const_lv32_F = "1111";
const sc_lv<32> fir_filter::ap_const_lv32_FFFF0000 = "11111111111111110000000000000000";
const sc_lv<32> fir_filter::ap_const_lv32_2E = "101110";

fir_filter::fir_filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    shift_reg_left_V_U = new fir_filter_shift_bkb("shift_reg_left_V_U");
    shift_reg_left_V_U->clk(ap_clk);
    shift_reg_left_V_U->reset(ap_rst_n_inv);
    shift_reg_left_V_U->address0(shift_reg_left_V_address0);
    shift_reg_left_V_U->ce0(shift_reg_left_V_ce0);
    shift_reg_left_V_U->q0(shift_reg_left_V_q0);
    shift_reg_left_V_U->address1(shift_reg_left_V_address1);
    shift_reg_left_V_U->ce1(shift_reg_left_V_ce1);
    shift_reg_left_V_U->we1(shift_reg_left_V_we1);
    shift_reg_left_V_U->d1(shift_reg_left_V_d1);
    c_U = new fir_filter_c("c_U");
    c_U->clk(ap_clk);
    c_U->reset(ap_rst_n_inv);
    c_U->address0(c_address0);
    c_U->ce0(c_ce0);
    c_U->q0(c_q0);
    shift_reg_right_V_U = new fir_filter_shift_bkb("shift_reg_right_V_U");
    shift_reg_right_V_U->clk(ap_clk);
    shift_reg_right_V_U->reset(ap_rst_n_inv);
    shift_reg_right_V_U->address0(shift_reg_right_V_address0);
    shift_reg_right_V_U->ce0(shift_reg_right_V_ce0);
    shift_reg_right_V_U->q0(shift_reg_right_V_q0);
    shift_reg_right_V_U->address1(shift_reg_right_V_address1);
    shift_reg_right_V_U->ce1(shift_reg_right_V_ce1);
    shift_reg_right_V_U->we1(shift_reg_right_V_we1);
    shift_reg_right_V_U->d1(shift_reg_right_V_d1);
    regslice_both_datain_data_V_U = new regslice_both<32>("regslice_both_datain_data_V_U");
    regslice_both_datain_data_V_U->ap_clk(ap_clk);
    regslice_both_datain_data_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_datain_data_V_U->data_in(datain_TDATA);
    regslice_both_datain_data_V_U->vld_in(datain_TVALID);
    regslice_both_datain_data_V_U->ack_in(regslice_both_datain_data_V_U_ack_in);
    regslice_both_datain_data_V_U->data_out(datain_TDATA_int);
    regslice_both_datain_data_V_U->vld_out(datain_TVALID_int);
    regslice_both_datain_data_V_U->ack_out(datain_TREADY_int);
    regslice_both_datain_data_V_U->apdone_blk(regslice_both_datain_data_V_U_apdone_blk);
    regslice_both_datain_last_V_U = new regslice_both<1>("regslice_both_datain_last_V_U");
    regslice_both_datain_last_V_U->ap_clk(ap_clk);
    regslice_both_datain_last_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_datain_last_V_U->data_in(datain_TLAST);
    regslice_both_datain_last_V_U->vld_in(datain_TVALID);
    regslice_both_datain_last_V_U->ack_in(regslice_both_datain_last_V_U_ack_in);
    regslice_both_datain_last_V_U->data_out(datain_TLAST_int);
    regslice_both_datain_last_V_U->vld_out(regslice_both_datain_last_V_U_vld_out);
    regslice_both_datain_last_V_U->ack_out(datain_TREADY_int);
    regslice_both_datain_last_V_U->apdone_blk(regslice_both_datain_last_V_U_apdone_blk);
    regslice_both_dataout_data_V_U = new regslice_both<32>("regslice_both_dataout_data_V_U");
    regslice_both_dataout_data_V_U->ap_clk(ap_clk);
    regslice_both_dataout_data_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_dataout_data_V_U->data_in(dataout_TDATA_int);
    regslice_both_dataout_data_V_U->vld_in(dataout_TVALID_int);
    regslice_both_dataout_data_V_U->ack_in(dataout_TREADY_int);
    regslice_both_dataout_data_V_U->data_out(dataout_TDATA);
    regslice_both_dataout_data_V_U->vld_out(regslice_both_dataout_data_V_U_vld_out);
    regslice_both_dataout_data_V_U->ack_out(dataout_TREADY);
    regslice_both_dataout_data_V_U->apdone_blk(regslice_both_dataout_data_V_U_apdone_blk);
    regslice_both_dataout_last_V_U = new regslice_both<1>("regslice_both_dataout_last_V_U");
    regslice_both_dataout_last_V_U->ap_clk(ap_clk);
    regslice_both_dataout_last_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_dataout_last_V_U->data_in(dataout_TLAST_int);
    regslice_both_dataout_last_V_U->vld_in(dataout_TVALID_int);
    regslice_both_dataout_last_V_U->ack_in(regslice_both_dataout_last_V_U_ack_in_dummy);
    regslice_both_dataout_last_V_U->data_out(dataout_TLAST);
    regslice_both_dataout_last_V_U->vld_out(regslice_both_dataout_last_V_U_vld_out);
    regslice_both_dataout_last_V_U->ack_out(dataout_TREADY);
    regslice_both_dataout_last_V_U->apdone_blk(regslice_both_dataout_last_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_left_V_1_fu_337_p2);
    sensitive << ( trunc_ln51_fu_330_p1 );
    sensitive << ( sext_ln700_1_fu_334_p1 );

    SC_METHOD(thread_acc_left_V_2_fu_293_p2);
    sensitive << ( p_0403_0_reg_179 );
    sensitive << ( sext_ln700_4_fu_290_p1 );

    SC_METHOD(thread_acc_left_V_fu_245_p0);
    sensitive << ( reg_229 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_acc_left_V_fu_245_p2);
    sensitive << ( acc_left_V_fu_245_p0 );

    SC_METHOD(thread_acc_right_V_1_fu_450_p2);
    sensitive << ( trunc_ln98_fu_443_p1 );
    sensitive << ( sext_ln700_6_fu_447_p1 );

    SC_METHOD(thread_acc_right_V_2_fu_406_p2);
    sensitive << ( p_0412_0_reg_200 );
    sensitive << ( sext_ln700_9_fu_403_p1 );

    SC_METHOD(thread_acc_right_V_fu_358_p1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( reg_237 );

    SC_METHOD(thread_acc_right_V_fu_358_p2);
    sensitive << ( acc_right_V_fu_358_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_state13_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state14_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state15_pp1_stage0_iter2);

    SC_METHOD(thread_ap_block_state16_pp1_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter3);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state5);
    sensitive << ( icmp_ln51_fu_254_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state13);
    sensitive << ( icmp_ln98_fu_367_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_193_p4);
    sensitive << ( i_0_reg_189 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln51_reg_477 );
    sensitive << ( i_reg_481 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_i_1_phi_fu_214_p4);
    sensitive << ( i_1_reg_210 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln98_reg_542 );
    sensitive << ( i_2_reg_546 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_c_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln58_1_fu_271_p1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( zext_ln99_1_fu_384_p1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_c_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_datain_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( datain_TVALID_int );

    SC_METHOD(thread_datain_TREADY);
    sensitive << ( datain_TVALID );
    sensitive << ( regslice_both_datain_data_V_U_ack_in );

    SC_METHOD(thread_datain_TREADY_int);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( datain_TVALID_int );

    SC_METHOD(thread_datain_left_V_2_fu_313_p3);
    sensitive << ( tmp_2_fu_299_p3 );
    sensitive << ( datain_left_V_fu_307_p2 );
    sensitive << ( datain_TDATA_int );

    SC_METHOD(thread_datain_left_V_fu_307_p2);
    sensitive << ( datain_TDATA_int );

    SC_METHOD(thread_datain_right_V_2_fu_426_p3);
    sensitive << ( tmp_3_fu_412_p3 );
    sensitive << ( datain_right_V_fu_420_p2 );
    sensitive << ( datain_TDATA_int );

    SC_METHOD(thread_datain_right_V_fu_420_p2);
    sensitive << ( datain_TDATA_int );

    SC_METHOD(thread_dataout_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( dataout_TREADY_int );

    SC_METHOD(thread_dataout_TDATA_int);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( acc_left_V_1_fu_337_p2 );
    sensitive << ( acc_right_V_1_fu_450_p2 );

    SC_METHOD(thread_dataout_TLAST_int);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( datain_last_V_val_reg_511 );
    sensitive << ( datain_last_V_val8_reg_576 );

    SC_METHOD(thread_dataout_TVALID);
    sensitive << ( regslice_both_dataout_data_V_U_vld_out );

    SC_METHOD(thread_dataout_TVALID_int);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( dataout_TREADY_int );

    SC_METHOD(thread_i_2_fu_373_p2);
    sensitive << ( ap_phi_mux_i_1_phi_fu_214_p4 );

    SC_METHOD(thread_i_fu_260_p2);
    sensitive << ( ap_phi_mux_i_0_phi_fu_193_p4 );

    SC_METHOD(thread_icmp_ln51_fu_254_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_193_p4 );

    SC_METHOD(thread_icmp_ln98_fu_367_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_i_1_phi_fu_214_p4 );

    SC_METHOD(thread_mul_ln700_1_fu_324_p1);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( datain_left_V_2_reg_516 );

    SC_METHOD(thread_mul_ln700_1_fu_324_p2);
    sensitive << ( mul_ln700_1_fu_324_p1 );

    SC_METHOD(thread_mul_ln700_2_fu_397_p0);
    sensitive << ( reg_233 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_mul_ln700_2_fu_397_p1);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( sext_ln700_7_fu_389_p0 );

    SC_METHOD(thread_mul_ln700_2_fu_397_p2);
    sensitive << ( mul_ln700_2_fu_397_p0 );
    sensitive << ( mul_ln700_2_fu_397_p1 );

    SC_METHOD(thread_mul_ln700_3_fu_437_p1);
    sensitive << ( datain_right_V_2_reg_581 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_mul_ln700_3_fu_437_p2);
    sensitive << ( mul_ln700_3_fu_437_p1 );

    SC_METHOD(thread_mul_ln700_fu_284_p0);
    sensitive << ( reg_233 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln700_fu_284_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln700_2_fu_276_p0 );

    SC_METHOD(thread_mul_ln700_fu_284_p2);
    sensitive << ( mul_ln700_fu_284_p0 );
    sensitive << ( mul_ln700_fu_284_p1 );

    SC_METHOD(thread_sext_ln68_1_fu_251_p1);
    sensitive << ( acc_left_V_reg_467 );

    SC_METHOD(thread_sext_ln68_3_fu_364_p1);
    sensitive << ( acc_right_V_reg_532 );

    SC_METHOD(thread_sext_ln700_1_fu_334_p1);
    sensitive << ( mul_ln700_1_reg_522 );

    SC_METHOD(thread_sext_ln700_2_fu_276_p0);
    sensitive << ( reg_229 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln700_4_fu_290_p1);
    sensitive << ( mul_ln700_reg_501 );

    SC_METHOD(thread_sext_ln700_6_fu_447_p1);
    sensitive << ( mul_ln700_3_reg_587 );

    SC_METHOD(thread_sext_ln700_7_fu_389_p0);
    sensitive << ( reg_237 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_sext_ln700_9_fu_403_p1);
    sensitive << ( mul_ln700_2_reg_566 );

    SC_METHOD(thread_shift_reg_left_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln58_fu_266_p1 );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_shift_reg_left_V_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( zext_ln58_1_reg_491 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shift_reg_left_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_shift_reg_left_V_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_shift_reg_left_V_d1);
    sensitive << ( shift_reg_left_V_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( datain_left_V_2_reg_516 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shift_reg_left_V_we1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln51_reg_477 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_shift_reg_right_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln99_fu_379_p1 );

    SC_METHOD(thread_shift_reg_right_V_address1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( zext_ln99_1_reg_556 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_shift_reg_right_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( datain_TVALID_int );

    SC_METHOD(thread_shift_reg_right_V_ce1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_shift_reg_right_V_d1);
    sensitive << ( shift_reg_right_V_q0 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( datain_right_V_2_reg_581 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_shift_reg_right_V_we1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( icmp_ln98_reg_542 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_tmp_2_fu_299_p3);
    sensitive << ( datain_TDATA_int );

    SC_METHOD(thread_tmp_3_fu_412_p3);
    sensitive << ( datain_TDATA_int );

    SC_METHOD(thread_trunc_ln51_fu_330_p1);
    sensitive << ( p_0403_0_reg_179 );

    SC_METHOD(thread_trunc_ln98_fu_443_p1);
    sensitive << ( p_0412_0_reg_200 );

    SC_METHOD(thread_zext_ln58_1_fu_271_p1);
    sensitive << ( ap_phi_mux_i_0_phi_fu_193_p4 );

    SC_METHOD(thread_zext_ln58_fu_266_p1);
    sensitive << ( i_fu_260_p2 );

    SC_METHOD(thread_zext_ln99_1_fu_384_p1);
    sensitive << ( ap_phi_mux_i_1_phi_fu_214_p4 );

    SC_METHOD(thread_zext_ln99_fu_379_p1);
    sensitive << ( i_2_fu_373_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln51_fu_254_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln98_fu_367_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( regslice_both_dataout_data_V_U_apdone_blk );
    sensitive << ( datain_TVALID_int );
    sensitive << ( dataout_TREADY_int );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000000000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fir_filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, datain_TDATA, "(port)datain_TDATA");
    sc_trace(mVcdFile, datain_TVALID, "(port)datain_TVALID");
    sc_trace(mVcdFile, datain_TREADY, "(port)datain_TREADY");
    sc_trace(mVcdFile, datain_TLAST, "(port)datain_TLAST");
    sc_trace(mVcdFile, dataout_TDATA, "(port)dataout_TDATA");
    sc_trace(mVcdFile, dataout_TVALID, "(port)dataout_TVALID");
    sc_trace(mVcdFile, dataout_TREADY, "(port)dataout_TREADY");
    sc_trace(mVcdFile, dataout_TLAST, "(port)dataout_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, shift_reg_left_V_address0, "shift_reg_left_V_address0");
    sc_trace(mVcdFile, shift_reg_left_V_ce0, "shift_reg_left_V_ce0");
    sc_trace(mVcdFile, shift_reg_left_V_q0, "shift_reg_left_V_q0");
    sc_trace(mVcdFile, shift_reg_left_V_address1, "shift_reg_left_V_address1");
    sc_trace(mVcdFile, shift_reg_left_V_ce1, "shift_reg_left_V_ce1");
    sc_trace(mVcdFile, shift_reg_left_V_we1, "shift_reg_left_V_we1");
    sc_trace(mVcdFile, shift_reg_left_V_d1, "shift_reg_left_V_d1");
    sc_trace(mVcdFile, c_address0, "c_address0");
    sc_trace(mVcdFile, c_ce0, "c_ce0");
    sc_trace(mVcdFile, c_q0, "c_q0");
    sc_trace(mVcdFile, shift_reg_right_V_address0, "shift_reg_right_V_address0");
    sc_trace(mVcdFile, shift_reg_right_V_ce0, "shift_reg_right_V_ce0");
    sc_trace(mVcdFile, shift_reg_right_V_q0, "shift_reg_right_V_q0");
    sc_trace(mVcdFile, shift_reg_right_V_address1, "shift_reg_right_V_address1");
    sc_trace(mVcdFile, shift_reg_right_V_ce1, "shift_reg_right_V_ce1");
    sc_trace(mVcdFile, shift_reg_right_V_we1, "shift_reg_right_V_we1");
    sc_trace(mVcdFile, shift_reg_right_V_d1, "shift_reg_right_V_d1");
    sc_trace(mVcdFile, datain_TDATA_blk_n, "datain_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, dataout_TDATA_blk_n, "dataout_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, p_0403_0_reg_179, "p_0403_0_reg_179");
    sc_trace(mVcdFile, i_0_reg_189, "i_0_reg_189");
    sc_trace(mVcdFile, p_0412_0_reg_200, "p_0412_0_reg_200");
    sc_trace(mVcdFile, i_1_reg_210, "i_1_reg_210");
    sc_trace(mVcdFile, reg_229, "reg_229");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter0, "ap_block_state5_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter2, "ap_block_state7_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter3, "ap_block_state8_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln51_reg_477, "icmp_ln51_reg_477");
    sc_trace(mVcdFile, reg_233, "reg_233");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_state13_pp1_stage0_iter0, "ap_block_state13_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state14_pp1_stage0_iter1, "ap_block_state14_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state15_pp1_stage0_iter2, "ap_block_state15_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state16_pp1_stage0_iter3, "ap_block_state16_pp1_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, icmp_ln98_reg_542, "icmp_ln98_reg_542");
    sc_trace(mVcdFile, reg_237, "reg_237");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, acc_left_V_fu_245_p2, "acc_left_V_fu_245_p2");
    sc_trace(mVcdFile, acc_left_V_reg_467, "acc_left_V_reg_467");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, sext_ln68_1_fu_251_p1, "sext_ln68_1_fu_251_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln51_fu_254_p2, "icmp_ln51_fu_254_p2");
    sc_trace(mVcdFile, icmp_ln51_reg_477_pp0_iter1_reg, "icmp_ln51_reg_477_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln51_reg_477_pp0_iter2_reg, "icmp_ln51_reg_477_pp0_iter2_reg");
    sc_trace(mVcdFile, i_fu_260_p2, "i_fu_260_p2");
    sc_trace(mVcdFile, i_reg_481, "i_reg_481");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, zext_ln58_1_fu_271_p1, "zext_ln58_1_fu_271_p1");
    sc_trace(mVcdFile, zext_ln58_1_reg_491, "zext_ln58_1_reg_491");
    sc_trace(mVcdFile, mul_ln700_fu_284_p2, "mul_ln700_fu_284_p2");
    sc_trace(mVcdFile, mul_ln700_reg_501, "mul_ln700_reg_501");
    sc_trace(mVcdFile, acc_left_V_2_fu_293_p2, "acc_left_V_2_fu_293_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, datain_last_V_val_reg_511, "datain_last_V_val_reg_511");
    sc_trace(mVcdFile, datain_left_V_2_fu_313_p3, "datain_left_V_2_fu_313_p3");
    sc_trace(mVcdFile, datain_left_V_2_reg_516, "datain_left_V_2_reg_516");
    sc_trace(mVcdFile, mul_ln700_1_fu_324_p2, "mul_ln700_1_fu_324_p2");
    sc_trace(mVcdFile, mul_ln700_1_reg_522, "mul_ln700_1_reg_522");
    sc_trace(mVcdFile, acc_right_V_fu_358_p2, "acc_right_V_fu_358_p2");
    sc_trace(mVcdFile, acc_right_V_reg_532, "acc_right_V_reg_532");
    sc_trace(mVcdFile, sext_ln68_3_fu_364_p1, "sext_ln68_3_fu_364_p1");
    sc_trace(mVcdFile, icmp_ln98_fu_367_p2, "icmp_ln98_fu_367_p2");
    sc_trace(mVcdFile, icmp_ln98_reg_542_pp1_iter1_reg, "icmp_ln98_reg_542_pp1_iter1_reg");
    sc_trace(mVcdFile, icmp_ln98_reg_542_pp1_iter2_reg, "icmp_ln98_reg_542_pp1_iter2_reg");
    sc_trace(mVcdFile, i_2_fu_373_p2, "i_2_fu_373_p2");
    sc_trace(mVcdFile, i_2_reg_546, "i_2_reg_546");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, zext_ln99_1_fu_384_p1, "zext_ln99_1_fu_384_p1");
    sc_trace(mVcdFile, zext_ln99_1_reg_556, "zext_ln99_1_reg_556");
    sc_trace(mVcdFile, mul_ln700_2_fu_397_p2, "mul_ln700_2_fu_397_p2");
    sc_trace(mVcdFile, mul_ln700_2_reg_566, "mul_ln700_2_reg_566");
    sc_trace(mVcdFile, acc_right_V_2_fu_406_p2, "acc_right_V_2_fu_406_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter3, "ap_enable_reg_pp1_iter3");
    sc_trace(mVcdFile, datain_last_V_val8_reg_576, "datain_last_V_val8_reg_576");
    sc_trace(mVcdFile, datain_right_V_2_fu_426_p3, "datain_right_V_2_fu_426_p3");
    sc_trace(mVcdFile, datain_right_V_2_reg_581, "datain_right_V_2_reg_581");
    sc_trace(mVcdFile, mul_ln700_3_fu_437_p2, "mul_ln700_3_fu_437_p2");
    sc_trace(mVcdFile, mul_ln700_3_reg_587, "mul_ln700_3_reg_587");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state5, "ap_condition_pp0_exit_iter0_state5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state13, "ap_condition_pp1_exit_iter0_state13");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_193_p4, "ap_phi_mux_i_0_phi_fu_193_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_i_1_phi_fu_214_p4, "ap_phi_mux_i_1_phi_fu_214_p4");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, zext_ln58_fu_266_p1, "zext_ln58_fu_266_p1");
    sc_trace(mVcdFile, zext_ln99_fu_379_p1, "zext_ln99_fu_379_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, acc_left_V_fu_245_p0, "acc_left_V_fu_245_p0");
    sc_trace(mVcdFile, sext_ln700_2_fu_276_p0, "sext_ln700_2_fu_276_p0");
    sc_trace(mVcdFile, mul_ln700_fu_284_p0, "mul_ln700_fu_284_p0");
    sc_trace(mVcdFile, mul_ln700_fu_284_p1, "mul_ln700_fu_284_p1");
    sc_trace(mVcdFile, sext_ln700_4_fu_290_p1, "sext_ln700_4_fu_290_p1");
    sc_trace(mVcdFile, tmp_2_fu_299_p3, "tmp_2_fu_299_p3");
    sc_trace(mVcdFile, datain_left_V_fu_307_p2, "datain_left_V_fu_307_p2");
    sc_trace(mVcdFile, mul_ln700_1_fu_324_p1, "mul_ln700_1_fu_324_p1");
    sc_trace(mVcdFile, trunc_ln51_fu_330_p1, "trunc_ln51_fu_330_p1");
    sc_trace(mVcdFile, sext_ln700_1_fu_334_p1, "sext_ln700_1_fu_334_p1");
    sc_trace(mVcdFile, acc_left_V_1_fu_337_p2, "acc_left_V_1_fu_337_p2");
    sc_trace(mVcdFile, acc_right_V_fu_358_p1, "acc_right_V_fu_358_p1");
    sc_trace(mVcdFile, sext_ln700_7_fu_389_p0, "sext_ln700_7_fu_389_p0");
    sc_trace(mVcdFile, mul_ln700_2_fu_397_p0, "mul_ln700_2_fu_397_p0");
    sc_trace(mVcdFile, mul_ln700_2_fu_397_p1, "mul_ln700_2_fu_397_p1");
    sc_trace(mVcdFile, sext_ln700_9_fu_403_p1, "sext_ln700_9_fu_403_p1");
    sc_trace(mVcdFile, tmp_3_fu_412_p3, "tmp_3_fu_412_p3");
    sc_trace(mVcdFile, datain_right_V_fu_420_p2, "datain_right_V_fu_420_p2");
    sc_trace(mVcdFile, mul_ln700_3_fu_437_p1, "mul_ln700_3_fu_437_p1");
    sc_trace(mVcdFile, trunc_ln98_fu_443_p1, "trunc_ln98_fu_443_p1");
    sc_trace(mVcdFile, sext_ln700_6_fu_447_p1, "sext_ln700_6_fu_447_p1");
    sc_trace(mVcdFile, acc_right_V_1_fu_450_p2, "acc_right_V_1_fu_450_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, regslice_both_dataout_data_V_U_apdone_blk, "regslice_both_dataout_data_V_U_apdone_blk");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, regslice_both_datain_data_V_U_apdone_blk, "regslice_both_datain_data_V_U_apdone_blk");
    sc_trace(mVcdFile, datain_TDATA_int, "datain_TDATA_int");
    sc_trace(mVcdFile, datain_TVALID_int, "datain_TVALID_int");
    sc_trace(mVcdFile, datain_TREADY_int, "datain_TREADY_int");
    sc_trace(mVcdFile, regslice_both_datain_data_V_U_ack_in, "regslice_both_datain_data_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_datain_last_V_U_apdone_blk, "regslice_both_datain_last_V_U_apdone_blk");
    sc_trace(mVcdFile, datain_TLAST_int, "datain_TLAST_int");
    sc_trace(mVcdFile, regslice_both_datain_last_V_U_vld_out, "regslice_both_datain_last_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_datain_last_V_U_ack_in, "regslice_both_datain_last_V_U_ack_in");
    sc_trace(mVcdFile, dataout_TDATA_int, "dataout_TDATA_int");
    sc_trace(mVcdFile, dataout_TVALID_int, "dataout_TVALID_int");
    sc_trace(mVcdFile, dataout_TREADY_int, "dataout_TREADY_int");
    sc_trace(mVcdFile, regslice_both_dataout_data_V_U_vld_out, "regslice_both_dataout_data_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_dataout_last_V_U_apdone_blk, "regslice_both_dataout_last_V_U_apdone_blk");
    sc_trace(mVcdFile, dataout_TLAST_int, "dataout_TLAST_int");
    sc_trace(mVcdFile, regslice_both_dataout_last_V_U_ack_in_dummy, "regslice_both_dataout_last_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_dataout_last_V_U_vld_out, "regslice_both_dataout_last_V_U_vld_out");
#endif

    }
    mHdltvinHandle.open("fir_filter.hdltvin.dat");
    mHdltvoutHandle.open("fir_filter.hdltvout.dat");
}

fir_filter::~fir_filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete shift_reg_left_V_U;
    delete c_U;
    delete shift_reg_right_V_U;
    delete regslice_both_datain_data_V_U;
    delete regslice_both_datain_last_V_U;
    delete regslice_both_dataout_data_V_U;
    delete regslice_both_dataout_last_V_U;
}

void fir_filter::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state5.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state5.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state5.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
            ap_enable_reg_pp0_iter3 = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state13.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                    esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state13.read())) {
                ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state13.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter3 = ap_enable_reg_pp1_iter2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                    esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1))) {
            ap_enable_reg_pp1_iter3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln51_reg_477.read(), ap_const_lv1_0))) {
        i_0_reg_189 = i_reg_481.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_0_reg_189 = ap_const_lv6_39;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_reg_542.read()))) {
        i_1_reg_210 = i_2_reg_546.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1))) {
        i_1_reg_210 = ap_const_lv6_39;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_reg_477_pp0_iter2_reg.read()))) {
        p_0403_0_reg_179 = acc_left_V_2_fu_293_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_0403_0_reg_179 = sext_ln68_1_fu_251_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_reg_542_pp1_iter2_reg.read()))) {
        p_0412_0_reg_200 = acc_right_V_2_fu_406_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1))) {
        p_0412_0_reg_200 = sext_ln68_3_fu_364_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        acc_left_V_reg_467 = acc_left_V_fu_245_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1))) {
        acc_right_V_reg_532 = acc_right_V_fu_358_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(datain_TVALID_int.read(), ap_const_logic_1))) {
        datain_last_V_val8_reg_576 = datain_TLAST_int.read();
        datain_right_V_2_reg_581 = datain_right_V_2_fu_426_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(datain_TVALID_int.read(), ap_const_logic_1))) {
        datain_last_V_val_reg_511 = datain_TLAST_int.read();
        datain_left_V_2_reg_516 = datain_left_V_2_fu_313_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_367_p2.read()))) {
        i_2_reg_546 = i_2_fu_373_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_fu_254_p2.read()))) {
        i_reg_481 = i_fu_260_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln51_reg_477 = icmp_ln51_fu_254_p2.read();
        icmp_ln51_reg_477_pp0_iter1_reg = icmp_ln51_reg_477.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln51_reg_477_pp0_iter2_reg = icmp_ln51_reg_477_pp0_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln98_reg_542 = icmp_ln98_fu_367_p2.read();
        icmp_ln98_reg_542_pp1_iter1_reg = icmp_ln98_reg_542.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln98_reg_542_pp1_iter2_reg = icmp_ln98_reg_542_pp1_iter1_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        mul_ln700_1_reg_522 = mul_ln700_1_fu_324_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_reg_542_pp1_iter1_reg.read()))) {
        mul_ln700_2_reg_566 = mul_ln700_2_fu_397_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        mul_ln700_3_reg_587 = mul_ln700_3_fu_437_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_reg_477_pp0_iter1_reg.read()))) {
        mul_ln700_reg_501 = mul_ln700_fu_284_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln51_reg_477.read(), ap_const_lv1_0)))) {
        reg_229 = shift_reg_left_V_q0.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln51_reg_477.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_reg_542.read())))) {
        reg_233 = c_q0.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_reg_542.read())) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        reg_237 = shift_reg_right_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_fu_254_p2.read()))) {
        zext_ln58_1_reg_491 = zext_ln58_1_fu_271_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_367_p2.read()))) {
        zext_ln99_1_reg_556 = zext_ln99_1_fu_384_p1.read();
    }
}

void fir_filter::thread_acc_left_V_1_fu_337_p2() {
    acc_left_V_1_fu_337_p2 = (!trunc_ln51_fu_330_p1.read().is_01() || !sext_ln700_1_fu_334_p1.read().is_01())? sc_lv<47>(): (sc_biguint<47>(trunc_ln51_fu_330_p1.read()) + sc_bigint<47>(sext_ln700_1_fu_334_p1.read()));
}

void fir_filter::thread_acc_left_V_2_fu_293_p2() {
    acc_left_V_2_fu_293_p2 = (!p_0403_0_reg_179.read().is_01() || !sext_ln700_4_fu_290_p1.read().is_01())? sc_lv<53>(): (sc_biguint<53>(p_0403_0_reg_179.read()) + sc_bigint<53>(sext_ln700_4_fu_290_p1.read()));
}

void fir_filter::thread_acc_left_V_fu_245_p0() {
    acc_left_V_fu_245_p0 = reg_229.read();
}

void fir_filter::thread_acc_left_V_fu_245_p2() {
    acc_left_V_fu_245_p2 = (!acc_left_V_fu_245_p0.read().is_01() || !ap_const_lv42_3FFFFFFFE86.is_01())? sc_lv<42>(): sc_bigint<32>(acc_left_V_fu_245_p0.read()) * sc_bigint<42>(ap_const_lv42_3FFFFFFFE86);
}

void fir_filter::thread_acc_right_V_1_fu_450_p2() {
    acc_right_V_1_fu_450_p2 = (!trunc_ln98_fu_443_p1.read().is_01() || !sext_ln700_6_fu_447_p1.read().is_01())? sc_lv<47>(): (sc_biguint<47>(trunc_ln98_fu_443_p1.read()) + sc_bigint<47>(sext_ln700_6_fu_447_p1.read()));
}

void fir_filter::thread_acc_right_V_2_fu_406_p2() {
    acc_right_V_2_fu_406_p2 = (!p_0412_0_reg_200.read().is_01() || !sext_ln700_9_fu_403_p1.read().is_01())? sc_lv<53>(): (sc_biguint<53>(p_0412_0_reg_200.read()) + sc_bigint<53>(sext_ln700_9_fu_403_p1.read()));
}

void fir_filter::thread_acc_right_V_fu_358_p1() {
    acc_right_V_fu_358_p1 = reg_237.read();
}

void fir_filter::thread_acc_right_V_fu_358_p2() {
    acc_right_V_fu_358_p2 = (!ap_const_lv42_3FFFFFFFE86.is_01() || !acc_right_V_fu_358_p1.read().is_01())? sc_lv<42>(): sc_bigint<42>(ap_const_lv42_3FFFFFFFE86) * sc_bigint<32>(acc_right_V_fu_358_p1.read());
}

void fir_filter::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[4];
}

void fir_filter::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[9];
}

void fir_filter::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fir_filter::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[6];
}

void fir_filter::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[7];
}

void fir_filter::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[8];
}

void fir_filter::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[10];
}

void fir_filter::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[11];
}

void fir_filter::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[12];
}

void fir_filter::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fir_filter::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[13];
}

void fir_filter::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void fir_filter::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void fir_filter::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[5];
}

void fir_filter::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_state13_pp1_stage0_iter0() {
    ap_block_state13_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_state14_pp1_stage0_iter1() {
    ap_block_state14_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_state15_pp1_stage0_iter2() {
    ap_block_state15_pp1_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_state16_pp1_stage0_iter3() {
    ap_block_state16_pp1_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_state5_pp0_stage0_iter0() {
    ap_block_state5_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_state7_pp0_stage0_iter2() {
    ap_block_state7_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_block_state8_pp0_stage0_iter3() {
    ap_block_state8_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void fir_filter::thread_ap_condition_pp0_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(icmp_ln51_fu_254_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state5 = ap_const_logic_0;
    }
}

void fir_filter::thread_ap_condition_pp1_exit_iter0_state13() {
    if (esl_seteq<1,1,1>(icmp_ln98_fu_367_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state13 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state13 = ap_const_logic_0;
    }
}

void fir_filter::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void fir_filter::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void fir_filter::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void fir_filter::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter3.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void fir_filter::thread_ap_phi_mux_i_0_phi_fu_193_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln51_reg_477.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_0_phi_fu_193_p4 = i_reg_481.read();
    } else {
        ap_phi_mux_i_0_phi_fu_193_p4 = i_0_reg_189.read();
    }
}

void fir_filter::thread_ap_phi_mux_i_1_phi_fu_214_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_reg_542.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_1_phi_fu_214_p4 = i_2_reg_546.read();
    } else {
        ap_phi_mux_i_1_phi_fu_214_p4 = i_1_reg_210.read();
    }
}

void fir_filter::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void fir_filter::thread_c_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        c_address0 =  (sc_lv<6>) (zext_ln99_1_fu_384_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        c_address0 =  (sc_lv<6>) (zext_ln58_1_fu_271_p1.read());
    } else {
        c_address0 = "XXXXXX";
    }
}

void fir_filter::thread_c_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())))) {
        c_ce0 = ap_const_logic_1;
    } else {
        c_ce0 = ap_const_logic_0;
    }
}

void fir_filter::thread_datain_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        datain_TDATA_blk_n = datain_TVALID_int.read();
    } else {
        datain_TDATA_blk_n = ap_const_logic_1;
    }
}

void fir_filter::thread_datain_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, datain_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_datain_data_V_U_ack_in.read()))) {
        datain_TREADY = ap_const_logic_1;
    } else {
        datain_TREADY = ap_const_logic_0;
    }
}

void fir_filter::thread_datain_TREADY_int() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
          esl_seteq<1,1,1>(datain_TVALID_int.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(datain_TVALID_int.read(), ap_const_logic_1)))) {
        datain_TREADY_int = ap_const_logic_1;
    } else {
        datain_TREADY_int = ap_const_logic_0;
    }
}

void fir_filter::thread_datain_left_V_2_fu_313_p3() {
    datain_left_V_2_fu_313_p3 = (!tmp_2_fu_299_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_2_fu_299_p3.read()[0].to_bool())? datain_left_V_fu_307_p2.read(): datain_TDATA_int.read());
}

void fir_filter::thread_datain_left_V_fu_307_p2() {
    datain_left_V_fu_307_p2 = (datain_TDATA_int.read() | ap_const_lv32_FFFF0000);
}

void fir_filter::thread_datain_right_V_2_fu_426_p3() {
    datain_right_V_2_fu_426_p3 = (!tmp_3_fu_412_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_412_p3.read()[0].to_bool())? datain_right_V_fu_420_p2.read(): datain_TDATA_int.read());
}

void fir_filter::thread_datain_right_V_fu_420_p2() {
    datain_right_V_fu_420_p2 = (datain_TDATA_int.read() | ap_const_lv32_FFFF0000);
}

void fir_filter::thread_dataout_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        dataout_TDATA_blk_n = dataout_TREADY_int.read();
    } else {
        dataout_TDATA_blk_n = ap_const_logic_1;
    }
}

void fir_filter::thread_dataout_TDATA_int() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        dataout_TDATA_int = acc_right_V_1_fu_450_p2.read().range(46, 15);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        dataout_TDATA_int = acc_left_V_1_fu_337_p2.read().range(46, 15);
    } else {
        dataout_TDATA_int =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fir_filter::thread_dataout_TLAST_int() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        dataout_TLAST_int = datain_last_V_val8_reg_576.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        dataout_TLAST_int = datain_last_V_val_reg_511.read();
    } else {
        dataout_TLAST_int =  (sc_lv<1>) ("X");
    }
}

void fir_filter::thread_dataout_TVALID() {
    dataout_TVALID = regslice_both_dataout_data_V_U_vld_out.read();
}

void fir_filter::thread_dataout_TVALID_int() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
          esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1)))) {
        dataout_TVALID_int = ap_const_logic_1;
    } else {
        dataout_TVALID_int = ap_const_logic_0;
    }
}

void fir_filter::thread_i_2_fu_373_p2() {
    i_2_fu_373_p2 = (!ap_phi_mux_i_1_phi_fu_214_p4.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(ap_phi_mux_i_1_phi_fu_214_p4.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void fir_filter::thread_i_fu_260_p2() {
    i_fu_260_p2 = (!ap_phi_mux_i_0_phi_fu_193_p4.read().is_01() || !ap_const_lv6_3F.is_01())? sc_lv<6>(): (sc_biguint<6>(ap_phi_mux_i_0_phi_fu_193_p4.read()) + sc_bigint<6>(ap_const_lv6_3F));
}

void fir_filter::thread_icmp_ln51_fu_254_p2() {
    icmp_ln51_fu_254_p2 = (!ap_phi_mux_i_0_phi_fu_193_p4.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_0_phi_fu_193_p4.read() == ap_const_lv6_0);
}

void fir_filter::thread_icmp_ln98_fu_367_p2() {
    icmp_ln98_fu_367_p2 = (!ap_phi_mux_i_1_phi_fu_214_p4.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_1_phi_fu_214_p4.read() == ap_const_lv6_0);
}

void fir_filter::thread_mul_ln700_1_fu_324_p1() {
    mul_ln700_1_fu_324_p1 = datain_left_V_2_reg_516.read();
}

void fir_filter::thread_mul_ln700_1_fu_324_p2() {
    mul_ln700_1_fu_324_p2 = (!ap_const_lv42_3FFFFFFFE86.is_01() || !mul_ln700_1_fu_324_p1.read().is_01())? sc_lv<42>(): sc_bigint<42>(ap_const_lv42_3FFFFFFFE86) * sc_bigint<32>(mul_ln700_1_fu_324_p1.read());
}

void fir_filter::thread_mul_ln700_2_fu_397_p0() {
    mul_ln700_2_fu_397_p0 = reg_233.read();
}

void fir_filter::thread_mul_ln700_2_fu_397_p1() {
    mul_ln700_2_fu_397_p1 = sext_ln700_7_fu_389_p0.read();
}

void fir_filter::thread_mul_ln700_2_fu_397_p2() {
    mul_ln700_2_fu_397_p2 = (!mul_ln700_2_fu_397_p0.read().is_01() || !mul_ln700_2_fu_397_p1.read().is_01())? sc_lv<48>(): sc_bigint<16>(mul_ln700_2_fu_397_p0.read()) * sc_bigint<32>(mul_ln700_2_fu_397_p1.read());
}

void fir_filter::thread_mul_ln700_3_fu_437_p1() {
    mul_ln700_3_fu_437_p1 = datain_right_V_2_reg_581.read();
}

void fir_filter::thread_mul_ln700_3_fu_437_p2() {
    mul_ln700_3_fu_437_p2 = (!ap_const_lv42_3FFFFFFFE86.is_01() || !mul_ln700_3_fu_437_p1.read().is_01())? sc_lv<42>(): sc_bigint<42>(ap_const_lv42_3FFFFFFFE86) * sc_bigint<32>(mul_ln700_3_fu_437_p1.read());
}

void fir_filter::thread_mul_ln700_fu_284_p0() {
    mul_ln700_fu_284_p0 = reg_233.read();
}

void fir_filter::thread_mul_ln700_fu_284_p1() {
    mul_ln700_fu_284_p1 = sext_ln700_2_fu_276_p0.read();
}

void fir_filter::thread_mul_ln700_fu_284_p2() {
    mul_ln700_fu_284_p2 = (!mul_ln700_fu_284_p0.read().is_01() || !mul_ln700_fu_284_p1.read().is_01())? sc_lv<48>(): sc_bigint<16>(mul_ln700_fu_284_p0.read()) * sc_bigint<32>(mul_ln700_fu_284_p1.read());
}

void fir_filter::thread_sext_ln68_1_fu_251_p1() {
    sext_ln68_1_fu_251_p1 = esl_sext<53,42>(acc_left_V_reg_467.read());
}

void fir_filter::thread_sext_ln68_3_fu_364_p1() {
    sext_ln68_3_fu_364_p1 = esl_sext<53,42>(acc_right_V_reg_532.read());
}

void fir_filter::thread_sext_ln700_1_fu_334_p1() {
    sext_ln700_1_fu_334_p1 = esl_sext<47,42>(mul_ln700_1_reg_522.read());
}

void fir_filter::thread_sext_ln700_2_fu_276_p0() {
    sext_ln700_2_fu_276_p0 = reg_229.read();
}

void fir_filter::thread_sext_ln700_4_fu_290_p1() {
    sext_ln700_4_fu_290_p1 = esl_sext<53,48>(mul_ln700_reg_501.read());
}

void fir_filter::thread_sext_ln700_6_fu_447_p1() {
    sext_ln700_6_fu_447_p1 = esl_sext<47,42>(mul_ln700_3_reg_587.read());
}

void fir_filter::thread_sext_ln700_7_fu_389_p0() {
    sext_ln700_7_fu_389_p0 = reg_237.read();
}

void fir_filter::thread_sext_ln700_9_fu_403_p1() {
    sext_ln700_9_fu_403_p1 = esl_sext<53,48>(mul_ln700_2_reg_566.read());
}

void fir_filter::thread_shift_reg_left_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        shift_reg_left_V_address0 =  (sc_lv<6>) (zext_ln58_fu_266_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        shift_reg_left_V_address0 = ap_const_lv6_39;
    } else {
        shift_reg_left_V_address0 = "XXXXXX";
    }
}

void fir_filter::thread_shift_reg_left_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        shift_reg_left_V_address1 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        shift_reg_left_V_address1 =  (sc_lv<6>) (zext_ln58_1_reg_491.read());
    } else {
        shift_reg_left_V_address1 = "XXXXXX";
    }
}

void fir_filter::thread_shift_reg_left_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        shift_reg_left_V_ce0 = ap_const_logic_1;
    } else {
        shift_reg_left_V_ce0 = ap_const_logic_0;
    }
}

void fir_filter::thread_shift_reg_left_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        shift_reg_left_V_ce1 = ap_const_logic_1;
    } else {
        shift_reg_left_V_ce1 = ap_const_logic_0;
    }
}

void fir_filter::thread_shift_reg_left_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        shift_reg_left_V_d1 = datain_left_V_2_reg_516.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        shift_reg_left_V_d1 = shift_reg_left_V_q0.read();
    } else {
        shift_reg_left_V_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fir_filter::thread_shift_reg_left_V_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln51_reg_477.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        shift_reg_left_V_we1 = ap_const_logic_1;
    } else {
        shift_reg_left_V_we1 = ap_const_logic_0;
    }
}

void fir_filter::thread_shift_reg_right_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        shift_reg_right_V_address0 =  (sc_lv<6>) (zext_ln99_fu_379_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        shift_reg_right_V_address0 = ap_const_lv6_39;
    } else {
        shift_reg_right_V_address0 = "XXXXXX";
    }
}

void fir_filter::thread_shift_reg_right_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        shift_reg_right_V_address1 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        shift_reg_right_V_address1 =  (sc_lv<6>) (zext_ln99_1_reg_556.read());
    } else {
        shift_reg_right_V_address1 = "XXXXXX";
    }
}

void fir_filter::thread_shift_reg_right_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(datain_TVALID_int.read(), ap_const_logic_1)))) {
        shift_reg_right_V_ce0 = ap_const_logic_1;
    } else {
        shift_reg_right_V_ce0 = ap_const_logic_0;
    }
}

void fir_filter::thread_shift_reg_right_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        shift_reg_right_V_ce1 = ap_const_logic_1;
    } else {
        shift_reg_right_V_ce1 = ap_const_logic_0;
    }
}

void fir_filter::thread_shift_reg_right_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        shift_reg_right_V_d1 = datain_right_V_2_reg_581.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        shift_reg_right_V_d1 = shift_reg_right_V_q0.read();
    } else {
        shift_reg_right_V_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void fir_filter::thread_shift_reg_right_V_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_reg_542.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        shift_reg_right_V_we1 = ap_const_logic_1;
    } else {
        shift_reg_right_V_we1 = ap_const_logic_0;
    }
}

void fir_filter::thread_tmp_2_fu_299_p3() {
    tmp_2_fu_299_p3 = datain_TDATA_int.read().range(15, 15);
}

void fir_filter::thread_tmp_3_fu_412_p3() {
    tmp_3_fu_412_p3 = datain_TDATA_int.read().range(15, 15);
}

void fir_filter::thread_trunc_ln51_fu_330_p1() {
    trunc_ln51_fu_330_p1 = p_0403_0_reg_179.read().range(47-1, 0);
}

void fir_filter::thread_trunc_ln98_fu_443_p1() {
    trunc_ln98_fu_443_p1 = p_0412_0_reg_200.read().range(47-1, 0);
}

void fir_filter::thread_zext_ln58_1_fu_271_p1() {
    zext_ln58_1_fu_271_p1 = esl_zext<64,6>(ap_phi_mux_i_0_phi_fu_193_p4.read());
}

void fir_filter::thread_zext_ln58_fu_266_p1() {
    zext_ln58_fu_266_p1 = esl_zext<64,6>(i_fu_260_p2.read());
}

void fir_filter::thread_zext_ln99_1_fu_384_p1() {
    zext_ln99_1_fu_384_p1 = esl_zext<64,6>(ap_phi_mux_i_1_phi_fu_214_p4.read());
}

void fir_filter::thread_zext_ln99_fu_379_p1() {
    zext_ln99_fu_379_p1 = esl_zext<64,6>(i_2_fu_373_p2.read());
}

void fir_filter::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 16 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln51_fu_254_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln51_fu_254_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(datain_TVALID_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 512 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln98_fu_367_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln98_fu_367_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(datain_TVALID_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && esl_seteq<1,1,1>(dataout_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_dataout_data_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_0, dataout_TREADY_int.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state20;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
            break;
    }
}

void fir_filter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"datain_TDATA\" :  \"" << datain_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"datain_TVALID\" :  \"" << datain_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"datain_TREADY\" :  \"" << datain_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"datain_TLAST\" :  \"" << datain_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dataout_TDATA\" :  \"" << dataout_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dataout_TVALID\" :  \"" << dataout_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dataout_TREADY\" :  \"" << dataout_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dataout_TLAST\" :  \"" << dataout_TLAST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

